package com.conordevilly.ocr.ocrcamera;

import java.io.ByteArrayOutputStream;

import com.conordevilly.ocr.ocrcamera.RestTask.AsyncResponse;

import android.app.Activity;
import android.app.AlertDialog;
import android.app.AlertDialog.Builder;
import android.content.Context;
import android.content.DialogInterface;
import android.content.Intent;
import android.graphics.Bitmap;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;
import android.os.Bundle;
import android.util.Base64;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;

/*
 * Android Application
 * User takes a picture which is sent back to the OCR Service
 * The service then sends a guess & displays the guess as a popup
 */
public class MainActivity extends Activity implements AsyncResponse{
	
	//TODO: Make point to dyndns
	private final String url = "http://147.252.143.171:8080/TestingREST";
	Intent intent;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		//setContentView(R.layout.activity_main);
		startCam();
	}
	
	public void startCam(){
		intent = new Intent(android.provider.MediaStore.ACTION_IMAGE_CAPTURE);
		startActivityForResult(intent, 0);
	}

	//Generated by Android
	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		// Inflate the menu; this adds items to the action bar if it is present.
		getMenuInflater().inflate(R.menu.main, menu);
		return true;
	}
	
	protected void onActivityResult(int requestCode, int resultCode, Intent data){
		super.onActivityResult(requestCode, resultCode, data);
		
		//Get the image the user took, convert it to byes
		Bitmap img = (Bitmap) data.getExtras().get("data");
		ByteArrayOutputStream baos = new ByteArrayOutputStream();  
		img.compress(Bitmap.CompressFormat.PNG , 100, baos); //bm is the bitmap object   

		//Encode the bytes as a Base64 string then set it 
		byte[] bytes = baos.toByteArray(); 
		String encoded = new String(Base64.encode(bytes, Base64.NO_WRAP));

		try {
			//Check connection available
			ConnectivityManager connMgr = (ConnectivityManager) getSystemService(Context.CONNECTIVITY_SERVICE);
			NetworkInfo networkInfo = connMgr.getActiveNetworkInfo();

			if (networkInfo != null && networkInfo.isConnected()) {
				new RestTask(url, MainActivity.this, this).execute(encoded);
			} else {
				Log.e("OCR", "No network connection available");
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	//Generated by Android
	@Override
	public boolean onOptionsItemSelected(MenuItem item) {
		// Handle action bar item clicks here. The action bar will
		// automatically handle clicks on the Home/Up button, so long
		// as you specify a parent activity in AndroidManifest.xml.
		int id = item.getItemId();
		if (id == R.id.action_settings) {
			return true;
		}
		return super.onOptionsItemSelected(item);
	}


	@Override
	public void processingFinished(String out) {
		Builder alertBuilder = new AlertDialog.Builder(this);
		AlertDialog dia = alertBuilder.create();
		dia.setTitle("Guess");
		dia.setMessage("Guess: " + out);

		dia.setButton(DialogInterface.BUTTON_POSITIVE, "Ok", new DialogInterface.OnClickListener() {
			@Override
			public void onClick(DialogInterface dialog, int which) {
				//Restart the camera
				startCam();
			}
		});
		dia.show();
	}
}
